language: cpp
compiler:
  - gcc
before_install:
 - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper qtbase5-dev qt5-default qtwebengine5-dev cdbs devscripts qtdeclarative5-dev
 - cd src
 - git clone git://github.com/vranki/libsiilihai.git
 - cd ..
 - qmake CONFIG+=with_lib
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - ville.ranki@iki.fi
  email:
    on_success: change
    on_failure: always

