name: siilihai-client
version: 2.7
summary: Siilihai web forum client
description: Siilihai web forum client
grade: stable
confinement: strict

apps:
  siilihai-client:
    command: desktop-launch $SNAP/usr/bin/siilihai-client
    plugs: [network,network-observe,x11,unity7,opengl,network-manager]

parts:
# See https://github.com/ubuntu/snapcraft-desktop-helpers/issues/62#issuecomment-310843827
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all

  libsiilihai:
    plugin: qmake
    source: https://github.com/vranki/libsiilihai.git
    source-type: git
    qt-version: qt5
    build-packages:
      - qtbase5-dev
      - build-essential
      - libqt5core5a
      - libqt5network5

  siilihai-client:
    plugin: qmake
    source: .
    qt-version: qt5
    build-packages:
      - build-essential
      - qtbase5-dev
      - libqt5core5a
      - libqt5network5
      - libqt5gui5
      - libqt5widgets5
    stage-packages:
      - libqt5gui5
      - libqt5webengine5
    after: [desktop-qt5, libsiilihai]

